"""mycelium.py — the pressure system: the forest listens to the work.

Each edit that fires PostToolUse propagates a signal through the enabled Home
buckets: entries semantically close to the edited file accumulate pressure.
After enough signals across enough sessions, the most-pressured entry surfaces
once via forage_mycelium — verbatim, unchanged — then goes quiet. This is the
mushroom: a mark that worked its way to the surface by being near real work, not
by being asked for.

The signal is the work, not the conversation. tick_neighbors fires on
PostToolUse (a file was actually edited), not on UserPromptSubmit (a message
was sent). The distinction matters: a prompt signal inflates pressure from
navigation and short replies; an edit signal inflates it only from real output.
Pressure built the wrong way from noise, not from work, would mean the threshold
is hit within a single session instead of across several — confetti instead of
signal.

THE ONE THING NOT TO DO HERE: do not write the surfaced body back into the
forest as a new entry. A re-stored mushroom is the second narrator — a voice
that sounds like memory but was generated by the surfacing, not by the work.
The body is returned; it is not stored. The corollary holds. (The hostile suite
proves it: test_forage_body_not_stored_back checks the row count before and
after foraging.)

Pressure UPDATEs are metadata writes on existing rows. They do not go through
_commit (the one write door for content inserts) because they create no new
memory entry and carry no provenance chain. The one-door firewall is intact.
"""

from __future__ import annotations

import numpy as np

from . import db, embed as _embed

# Cosine similarity gate for neighbor qualification. Unit-normalized vectors
# (embed.py) make cosine == dot product, but the gate is a cosine value so we
# compute it explicitly from the stored BLOB rather than inferring from the vec
# index's L2 distance. Both are monotonically related for unit vectors, but this
# makes the threshold honest. Tune after real session data accumulates.
COSINE_GATE = 0.60

# Effective pressure required to surface: neighbor_pressure + 2*surface_pressure.
# surface_pressure (set by explicit user action, future phase) is weighted 2×
# because it is a deliberate signal; neighbor_pressure is ambient. At 3, an
# entry needs three independent edit events near it before it surfaces — or one
# explicit surface_pressure increment plus one neighbor hit. Tune after data.
PRESSURE_THRESHOLD = 3


def tick_neighbors(
    conn, project: str, file_path: str, content: str, k: int = 8
) -> int:
    """Propagate an edit signal through the forest.

    Embeds file_path + content (the model truncates at its token limit; for
    Edit this is the changed span, which is exactly right; for Write it
    captures the file header, a reasonable document fingerprint). k-NNs every
    enabled Home bucket with an over-fetch to survive project and dismissed
    filtering. Cosine is computed from the stored embedding BLOB — see
    COSINE_GATE above for why we compute it explicitly rather than using the
    vec distance directly.

    Returns the count of entries whose pressure was incremented.
    """
    query = f"{file_path}\n{content}"
    qvec = _embed.embed(query)
    qblob = _embed.serialize(qvec)

    updated = 0
    for bucket in db.enabled_buckets(conn, "home"):
        tbl, vec = db._table_for(conn, bucket)
        rows = conn.execute(
            f"SELECT v.entry_id, c.embedding, c.project, c.dismissed "
            f"FROM {vec} v JOIN {tbl} c ON c.id = v.entry_id "
            f"WHERE v.embedding MATCH ? AND k = ?",
            (qblob, k * 3),  # over-fetch: project + cosine filter will shrink this
        ).fetchall()
        for row in rows:
            if row["project"] != project:
                continue
            if row["dismissed"]:
                continue
            if row["embedding"] is None:
                continue
            other = np.frombuffer(row["embedding"], dtype="<f4")
            if _embed.cosine(qvec, other) >= COSINE_GATE:
                conn.execute(
                    f"UPDATE {tbl} "
                    f"SET neighbor_pressure = neighbor_pressure + 1 "
                    f"WHERE id = ?",
                    (row["entry_id"],),
                )
                updated += 1
    if updated:
        conn.commit()
    return updated


def forage_mycelium(conn, project: str):
    """Surface the highest-pressure entry across all enabled Home buckets.

    The table-per-bucket schema means we cannot ORDER BY across tables in a
    single SQLite query; we find the per-bucket winner and track the global
    max. Resets both pressure counters on the winner so it goes quiet after
    this call — surfaces once, then silence.

    Returns None if no entry meets PRESSURE_THRESHOLD. Returns a dict with
    id, body, bucket, and pressure if one surfaces. The body is verbatim
    forest ground; see the module header for what must not happen to it.
    """
    best = None
    best_score = 0
    best_tbl = None
    best_bucket = None

    for bucket in db.enabled_buckets(conn, "home"):
        tbl, _ = db._table_for(conn, bucket)
        row = conn.execute(
            f"SELECT id, body, neighbor_pressure, surface_pressure "
            f"FROM {tbl} "
            f"WHERE project = ? AND dismissed = 0 "
            f"  AND (neighbor_pressure + 2 * surface_pressure) >= ? "
            f"ORDER BY (neighbor_pressure + 2 * surface_pressure) DESC "
            f"LIMIT 1",
            (project, PRESSURE_THRESHOLD),
        ).fetchone()
        if row is None:
            continue
        score = row["neighbor_pressure"] + 2 * row["surface_pressure"]
        if score > best_score:
            best_score = score
            best = row
            best_tbl = tbl
            best_bucket = bucket

    if best is None:
        return None

    conn.execute(
        f"UPDATE {best_tbl} SET neighbor_pressure = 0, surface_pressure = 0 "
        f"WHERE id = ?",
        (best["id"],),
    )
    conn.commit()

    return {
        "id": best["id"],
        "body": best["body"],
        "bucket": best_bucket,
        "pressure": best_score,
    }
