"""The handover stamp — the seat's gauges, grown from the LOG.

Earned 2026-07-01 after the departure breath caught the same drift three
times in one day: a keeper does LOG work, then hand-copies numbers into
HANDOFF.md, and the numbers are stale before the ink dries. The narrative
of a seat must stay human — no machine can say what a watch was like. But
the gauges (counts, latest ground, open DR plots) were never the keeper's
to transcribe. The forest knows its own trees.

`stamp` rewrites only the block between the gauge markers in HANDOFF.md,
reading everything from the substrate at that moment. Run it after the
narrative rewrite, before `breathe out`.
"""

from __future__ import annotations

import datetime as dt
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BEGIN = "<!-- gauges:begin (generated by `python -m lighthouse handover` — do not hand-edit) -->"
END = "<!-- gauges:end -->"


def render(conn: sqlite3.Connection, now: dt.datetime | None = None) -> str:
    now = now or dt.datetime.now(dt.timezone.utc)
    counts = {
        label: conn.execute(query).fetchone()[0]
        for label, query in (
            ("active fixes", "SELECT COUNT(*) FROM fix WHERE status='active'"),
            ("stale fixes", "SELECT COUNT(*) FROM fix WHERE status='stale'"),
            ("open DR plots", "SELECT COUNT(*) FROM chart WHERE status='open'"),
            ("audit entries", "SELECT COUNT(*) FROM fix_audit"),
        )
    }
    lines = [BEGIN,
             f"Gauges read {now.isoformat(timespec='seconds')} — "
             "live readings, not a photograph:",
             ""]
    lines += [f"- {label}: {n}" for label, n in counts.items()]
    latest = conn.execute(
        "SELECT claim, taken_at FROM fix WHERE status='active' "
        "ORDER BY taken_at DESC LIMIT 1").fetchone()
    if latest:
        lines.append(f"- newest ground: {latest['claim']} ({latest['taken_at']})")
    for row in conn.execute(
            "SELECT id, note FROM chart WHERE status='open' ORDER BY plotted_at"):
        lines.append(f"- open DR {row['id']}: {row['note']}")
    lines.append(END)
    return "\n".join(lines)


def stamp(conn: sqlite3.Connection, root: Path | None = None,
          now: dt.datetime | None = None) -> bool:
    """Regrow the gauge block in HANDOFF.md. Returns True if stamped."""
    root = root or ROOT
    handoff = root / "HANDOFF.md"
    if not handoff.exists():
        return False
    text = handoff.read_text(encoding="utf-8")
    block = render(conn, now)
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        text = head + block + tail
    else:
        # first stamping: gauges live directly under the title line
        lines = text.splitlines(keepends=True)
        insert_at = 1 if lines else 0
        lines.insert(insert_at, "\n" + block + "\n")
        text = "".join(lines)
    handoff.write_text(text, encoding="utf-8")
    return True
